/**
 * Site registry for multi-site job tracking.
 * Per-site: host match, title/company selectors, apply-success text patterns.
 * Maps to GamedIn ApplicationSource: linkedin | indeed | glassdoor | other
 */

const SITES = [
  {
    id: 'linkedin',
    source: 'linkedin',
    hosts: ['linkedin.com'],
    titleSelectors: [
      '.job-details-jobs-unified-top-card__job-title',
      '.job-details-top-card__job-title',
      '.jobs-unified-top-card__job-title',
      '.jobs-top-card__job-title',
      '.topcard__title',
      'h1.t-24',
      '[data-job-title]',
      '.base-search-card__title',
      '.job-card-list__title',
      'h1[class*="job"]',
      'h1[class*="title"]',
      '.jobs-details-top-card__job-title',
      'h1',
    ],
    companySelectors: [
      '.job-details-jobs-unified-top-card__company-name',
      '.job-details-top-card__company-url',
      '.job-details-top-card__company-info a',
      '.jobs-unified-top-card__company-name',
      '.jobs-top-card__company-url',
      '.topcard__org-name-link',
      '.base-search-card__subtitle',
      '[data-company-name]',
      'a[href*="/company/"]',
      '.job-details-top-card__company-url',
      '.job-details-top-card__company-name',
    ],
    successText: [
      'application sent',
      'your application was sent',
      'application submitted',
    ],
    skipCompany: ['company', 'see company', 'view company', 'learn more', 'companies', 'see company page', 'view all jobs'],
    activity: {
      search: { paramKeywords: 'keywords', paramLocation: 'location', paramJobId: 'currentJobId', urlMatch: '/jobs' },
      jobList: {
        cardSelector: '.job-card-container, .scaffold-layout__list-item [data-occludable-job-id], .jobs-search-results__list-item, [data-occludable-job-id]',
        titleSelector: '.base-search-card__title, .job-card-list__title, h3, [class*="title"]',
        companySelector: '.base-search-card__subtitle, [class*="company"]',
        idAttr: 'data-occludable-job-id',
      },
      jobClicked: {
        linkSelector: 'a[href*="/jobs/view/"], a[href*="currentJobId="], .job-card-container a, .base-card a, [data-job-id]',
        cardSelector: '.job-card-container, .base-card, [data-occludable-job-id], [data-job-id]',
        titleSelector: '.base-search-card__title, .job-card-list__title, h3, [class*="job-title"]',
        companySelector: '.base-search-card__subtitle, [class*="company"]',
        jobIdPattern: /currentJobId=(\d+)|(\d{8,})/,
      },
      jobViewed: { paramJobId: 'currentJobId', urlPattern: /currentJobId=(\d+)/ },
    },
  },
  {
    id: 'indeed',
    source: 'indeed',
    hosts: ['indeed.com', 'indeed.co.uk', 'indeed.ca', 'au.indeed.com'],
    titleSelectors: [
      '.jobsearch-JobInfoHeader-title',
      '[data-testid="jobsearch-JobInfoHeader-title"]',
      'h1.jobsearch-JobInfoHeader-title',
      '.jobsearch-ViewJob h1',
      'h1[class*="JobInfoHeader"]',
      'h1',
    ],
    companySelectors: [
      '[data-testid="inlineHeader-companyName"]',
      '.companyName',
      '[data-company-name]',
      'a[data-tn-element="companyName"]',
      '.jobsearch-CompanyInfoContainer a',
      'div[class*="companyName"]',
      'h2 + div a',
    ],
    successText: [
      'application submitted',
      'you applied',
      'application sent',
      'your application has been submitted',
      'thank you for applying',
    ],
    skipCompany: ['company', 'see company', 'view company', 'learn more'],
    activity: {
      search: { paramKeywords: 'q', paramLocation: 'l', urlMatch: '/jobs' },
      jobList: {
        cardSelector: '.job_seen_beacon, [data-jobkey], div[data-jk]',
        titleSelector: 'h2.jobTitle span, [data-testid="jobsearch-JobInfoHeader-title"], .jobTitle',
        companySelector: 'span.companyName, [data-testid="inlineHeader-companyName"]',
        idAttr: 'data-jk',
      },
      jobClicked: {
        linkSelector: 'a.tapItem, a[data-jk], a[href*="/viewjob"], a[href*="/rc/clk"]',
        cardSelector: '.job_seen_beacon, [data-jobkey]',
        titleSelector: 'h2.jobTitle span, .jobTitle',
        companySelector: 'span.companyName',
        jobIdPattern: /[?&]jk=([^&]+)|viewjob\?jk=([^&]+)/,
      },
      jobViewed: { paramJobId: 'jk', urlPattern: /viewjob\?jk=([^&]+)|[?&]jk=([^&]+)/ },
    },
  },
  {
    id: 'glassdoor',
    source: 'glassdoor',
    hosts: ['glassdoor.com', 'glassdoor.co.uk'],
    titleSelectors: [
      '[data-test="job-detail-header-title"]',
      '.jobDetailsHeader h1',
      '.JobDetails_jobDetailsHeader__title',
      'h1[class*="job"]',
      '.job-title',
      'h1',
    ],
    companySelectors: [
      '[data-test="job-detail-header-company"]',
      '.EmployerInfo__EmployerInfoHeader',
      'a[data-test="job-detail-header-company-link"]',
      '[class*="EmployerInfo"] a',
      '.jobEmpolyerName',
      '.jobEmployerName',
      'a[href*="/Overview/"]',
    ],
    successText: [
      'application submitted',
      'applied',
      'application sent',
      'thank you for applying',
      'your application has been submitted',
    ],
    skipCompany: ['company', 'see company', 'view company', 'learn more'],
    activity: {
      search: { urlMatch: '/Job/', pathKeywords: true },
      jobList: {
        cardSelector: '.react-job-listing, [data-test="job-listing"], .JobCard, .jobCard',
        titleSelector: '.jobLink, [data-test="job-listing-title"], .job-title, h2',
        companySelector: '.jobEmpolyerName, .jobEmployerName, [data-test="job-listing-company"]',
        idAttr: 'data-job-id',
      },
      jobClicked: {
        linkSelector: 'a.jobLink, a[href*="/job-details"], a[href*="/Job/"]',
        cardSelector: '.react-job-listing, .JobCard, .jobCard',
        titleSelector: '.jobLink, .job-title',
        companySelector: '.jobEmpolyerName, .jobEmployerName',
        jobIdPattern: /\/job-details\/([^/?]+)|Job\/([^/?]+)/,
      },
      jobViewed: { urlPattern: /\/job-details\/|Job\/[^/]+\d/ },
    },
  },
  {
    id: 'greenhouse',
    source: 'other',
    hosts: ['greenhouse.io', 'boards.greenhouse.io', 'jobs.greenhouse.io'],
    titleSelectors: [
      '.app-title',
      'h1.app-title',
      '[class*="app-title"]',
      '.job-title',
      'h1',
    ],
    companySelectors: [
      '.company-name',
      '[class*="company-name"]',
      '.company_name',
      'a[href*="/company/"]',
      'h2',
    ],
    successText: [
      'thank you',
      'application received',
      'application submitted',
      'your application has been submitted',
      'we have received your application',
    ],
    skipCompany: ['company', 'see company', 'view company'],
    activity: {
      jobList: {
        cardSelector: '.posting, .posting-card, [class*="posting"]',
        titleSelector: '.posting-headline, .posting-title, h4, h5',
        companySelector: '.posting-categories, .company-name',
        idAttr: 'data-gh-id',
      },
      jobClicked: {
        linkSelector: 'a.posting-title, a[href*="/jobs/"], a[href*="/job/"]',
        cardSelector: '.posting, .posting-card',
        titleSelector: '.posting-headline, .posting-title',
        companySelector: '.posting-categories',
        jobIdPattern: /\/jobs?\/([^/?]+)/,
      },
      jobViewed: { urlPattern: /\/jobs?\/([^/?]+)/ },
    },
  },
  {
    id: 'lever',
    source: 'other',
    hosts: ['jobs.lever.co', 'lever.co'],
    titleSelectors: [
      '.posting-headline',
      'h2.posting-headline',
      '[class*="posting-headline"]',
      '.posting-header h2',
      'h1',
    ],
    companySelectors: [
      '.posting-categories',
      'a[href*="/company/"]',
      '.main-header-logo',
      '[class*="company"]',
      'h1',
    ],
    successText: [
      'thank you',
      'application received',
      'application submitted',
      'your application has been submitted',
      'we have received your application',
    ],
    skipCompany: ['company', 'see company', 'view company'],
    activity: {
      jobList: {
        cardSelector: '.posting, .posting-card, [class*="posting"]',
        titleSelector: '.posting-headline, .posting-title, h4, h5',
        companySelector: '.posting-categories, .company-name',
        idAttr: 'data-posting-id',
      },
      jobClicked: {
        linkSelector: 'a.posting-title, a[href*="/jobs/"], a[href*="/job/"]',
        cardSelector: '.posting, .posting-card',
        titleSelector: '.posting-headline, .posting-title',
        companySelector: '.posting-categories',
        jobIdPattern: /\/jobs?\/([^/?]+)/,
      },
      jobViewed: { urlPattern: /\/jobs?\/([^/?]+)/ },
    },
  },
]

// Expose for jobParser (loaded after this script)
if (typeof window !== 'undefined') {
  window.GAMEDIN_SITES = SITES
}
